Update readme and contribution guidelines in project
10up/component-library pull request #43
Opened 2021-04-12 21:18 UTC by joesnellpdx

### Description of the Change

Updating readme and doc files to provide more clear direction to contributing engineers. There is more needed in the long term, but this should help. 

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### Still needed:

- all legacy repos need to be marked as deprecated and link to this repository. 
- release guidelines
- publish to npm guidelines
- update doc site to use latest release guidelines

2021-04-12 23:06 UTC, nicholasio requested changes
Thanks for the updated, just found some typos

2021-04-12 23:06 UTC, nicholasio commented on docs/getting-started.md
> +Naviate to the [docs](https://github.com/10up/component-library/tree/develop/docs) directory from the command line.
```suggestion
Navigate to the [docs](https://github.com/10up/component-library/tree/develop/docs) directory from the command line.
```

2021-04-12 23:06 UTC, nicholasio commented on packages/README.md
> +Engineers can work in that component and dest on components demo/index.html page or use the [e2e](../e2e) directory for local testing.
```suggestion
Engineers can work in that component and test on the components demo/index.html page or use the [e2e](../e2e) directory for local testing.
```

2021-04-12 23:52 UTC, joesnellpdx commented
> Thanks for the updated, just found some typos

Typos fixed. GRR! Sorry.

2021-04-13 00:14 UTC, nicholasio approved these changes

2021-04-13 00:14 UTC, merged